#!/bin/bash --
#https://forums.alliedmods.net/showthread.php?t=219697
LANG=C; LC_ALL=C; export LANG LC_ALL
iptables -F
iptables -X
iptables -P INPUT ACCEPT
iptables -P OUTPUT ACCEPT
iptables -P FORWARD ACCEPT

iptables -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
iptables -A INPUT -p tcp -m tcp --dport 42 -j ACCEPT

# Accept everything fromt he loopback device
iptables -A INPUT -i lo -j ACCEPT

# Accept stuff that has already been established or is related
iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

# Game Client Traffic + Matchmaking and HLTV
iptables -A INPUT -p udp -m udp --dport 27000:27130 -j ACCEPT
# Steam Downloads
iptables -A INPUT -p tcp -m tcp --dport 27014:27150 -j ACCEPT
# Other ports for Steam
iptables -A INPUT -p udp -m udp --dport 4380 -j ACCEPT
iptables -A INPUT -p udp -m udp --dport 3478 -j ACCEPT
iptables -A INPUT -p udp -m udp --dport 4379 -j ACCEPT
iptables -A INPUT -p udp -m udp --dport 4380 -j ACCEPT
iptables -A INPUT -p udp -m udp --dport 1200 -j ACCEPT


iptables -A INPUT -j DROP
iptables -A OUTPUT -p tcp -m tcp --sport 22 -j ACCEPT
iptables -A OUTPUT -p tcp -m tcp --sport 42 -j ACCEPT
# Always end a script the right way
exit 0

