#!/bin/sh

# The path to the game you want to host. example = /home/newuser/dod
DIR=/home/bill/servers/srcds/tf2
DAEMON=$DIR/srcds_run

# Change all PARAMS to your needs.
PARAMS="-game tf +map koth_viaduct -hostport 27015 +ip 0.0.0.0"
NAME=SRCDS
DESC="source dedicated server"

echo "Starting $DESC: $NAME"
if [ -e $DIR ]; then
    $DAEMON $PARAMS
else
    echo "No such directory: $DIR!"
fi
