#!/bin/sh
#Updates sourcemod for both srcds servers running sourcemod and also for my
#developoment copy to write and compile plugins

#Settings, update these
SOURCEMOD_DIR=addons/sourcemod/
SRCDS_TF2=/home/bill/servers/srcds/tf2/tf/$SOURCEMOD_DIR
DEV_DIR=~/current_work/sourcemod
TMP_DIR=$DEV_DIR/.tmp

mkdir -p $TMP_DIR
cd $TMP_DIR
wget -O smdrop15.html http://www.sourcemod.net/smdrop/1.5/
FILE=`egrep '"sourcemod-1\.5\..*-hg.*-linux\.tar\.gz"' smdrop15.html | cut -d '"' -f 2 | tail -1`
if [ -n "$FILE" -a ! -f "$FILE" ] ; then

	echo "Sourcemod is out of date, updating"
	wget http://www.sourcemod.net/smdrop/1.5/$FILE
	tar -xzf $FILE
	cd $SOURCEMOD_DIR

	echo "Copying to server's directory"
	#You can add more servers here
	cp -r `ls | grep -v configs` $SRCDS_TF2

	echo "Copying to development directory"
	rm -R $DEV_DIR/scripting
	cp -r scripting $DEV_DIR/

	echo "Copying smlib"
	cp -r ~/repo_dump/smlib/scripting/ $DEV_DIR/
fi
