#!/bin/sh

BUILD_DIR=/home/steam/sourcemod/
PLUGIN_DIR=addons/sourcemod/plugins/

build_server(){
    local server=$1
    SOURCEMOD_DEV_SERVER=$server
    cd $BUILD_DIR

    echo "#########################"
    echo "Building Server ($server)"
    echo "#########################"
}

build(){
    local dir=$1
    cd $dir
    rake clean
    rake compile | egrep --color "warning|error"
    rake install
    cd $BUILD_DIR
}

remove_disabled(){
    cd $SOURCEMOD_DEV_SERVER
    cd $PLUGIN_DIR
    for f in $(ls disabled) ; do
        rm -f $f
    done
}

#Jetpack Server #######################################
build_tf2_jet(){
    build_server /home/steam/steamcmd/tf2_jet/tf/

    build admin_support
    build advanced_ads
    build analytics
    build autoupdater
    build be_the_
    build dmr
    build goomba
    build hud_alerts
    build huntsman_air
    build iga
    build jet
    build nomgrep
    build other
    build rtd
    build super_ff
    build webshortcuts

    remove_disabled
}

#Stop That Tank Server #######################################
build_tf2_stt(){
    build_server /home/steam/steamcmd/tf2_stt/tf/

    build admin_support
    build advanced_ads
    build analytics
    build autoupdater
    build dmr
    build dhooks
    build goomba
    build hud_alerts
    build iga
    build jet
    build other
    build sendproxy
    build steamtools
    build stt
    build tf2items
    build webshortcuts

    remove_disabled
}

#Main Server #######################################
build_tf2_main(){
    build_server /home/steam/steamcmd/tf2_main/tf/

    build admin_support
    build advanced_ads
    build analytics
    build autoupdater
    build botmanager
    build botnames
    build iga
    build goomba
    build other

    remove_disabled
}

#L4D Server #######################################
build_l4d_main(){
    build_server /home/steam/steamcmd/l4d_main/left4dead/

    build admin_support
    build autoupdater
    build iga
    build jet

    remove_disabled
}

#L4D2 Server #######################################
build_l4d2_main(){
    build_server /home/steam/steamcmd/l4d2_main/left4dead2/

    build admin_support
    build autoupdater
    build crawling_l4d2
    build iga
    build jet
    build jockey_jump_l4d2
    build weapon_unlock_l4d2
    build zcs_l4d2

    remove_disabled
}

#NMRIH Server #######################################
build_nmrih_main(){
    build_server /home/steam/steamcmd/nmrih_main/nmrih/

    build admin_support
    build autoupdater
    build iga
    build nomgrep

    remove_disabled
}

#CSGO Server #######################################
build_csgo_main(){
    build_server /home/steam/steamcmd/csgo_main/csgo/

    build admin_support
    build advanced_ads
    build analytics
    build autoupdater
    build dmr
    build iga
    build jet
    build mapconfigs
    build webshortcuts

    remove_disabled
}

#Fists Full of Frags Server #######################################
build_fof_main(){
    build_server /home/steam/steamcmd/fof_main/fof/

    build admin_support
    build advanced_ads
    build analytics
    build autoupdater
    build death_chance_fof
    build dmr
    build drunk_fof
    build iga
    build jet
    build killer_info_display
    build mapconfigs
    build mapfix_fof
    build navfile_blocker
    build near_map_end_fof
    build randomize_teams_fof
    build resize_players
    build super_kick_fof
    build voice_warn
    #build weapon_mod
    build weapon_only_fof
    build webshortcuts
    build word_filter

    remove_disabled
}

#Fists Full of Frags Teamplay Server #######################################
build_fof_tp(){
    build_server /home/steam/steamcmd/fof_tp/fof/

    build admin_support
    build advanced_ads
    build analytics
    build autoupdater
    build death_chance_fof
    build dmr
    build drunk_fof
    build fashion_fof
    build gungame_fof
    build iga
    build jet
    build killer_info_display
    build mapconfigs
    build navfile_blocker
    build mapfix_fof
    build randomize_teams_fof
    build resize_players
    build super_kick_fof
    build voice_warn
    build webshortcuts
    build word_filter

    remove_disabled
}

#Fists Full of Frags Break Bad Server #######################################
build_fof_mk(){
    build_server /home/steam/steamcmd/fof_mk/fof/

    build admin_support
    build advanced_ads
    build analytics
    build autoupdater
    build death_chance_fof
    build dmr
    build drunk_fof
    #build fashion_fof
    build iga
    build jet
    build killer_info_display
    build mapconfigs
    build mapfix_fof
    build navfile_blocker
    build near_map_end_fof
    build randomize_teams_fof
    build resize_players
    build super_kick_fof
    build voice_warn
    build weapon_only_fof
    build webshortcuts
    build word_filter

    remove_disabled
}

# ###########################
build_ins_main(){
    build_server /home/steam/steamcmd/ins_main/insurgency/

    build admin_support

    remove_disabled
}




#Build list here###############

#build_tf2_jet
#build_l4d_main
#build_l4d2_main
build_fof_main
build_fof_tp
build_fof_mk
