#!/bin/bash

spcomp=$SOURCEMOD_DIR/addons/sourcemod/scripting/spcomp
failed=()

build_server(){
    local server=$1

    echo "#########################"
    echo "Building Server ($server)"
    echo "#########################"
}

build(){
    local dir=$1
    local srcds=$2

    echo "building $dir for $srcds"

    make all install -C$dir SPCOMP=$spcomp SPFLAGS="-v0" SRCDS=$srcds

    # use this instead for a dry run to find errors/warnings
    # make all -C$dir SPCOMP=$spcomp SPFLAGS="-v0 -E" SRCDS=$srcds

    if [ $? -eq 0 ]; then
      echo -e "\e[0;32mfinished $dir\e[0m";
    else
      echo -e "\e[1;31mfailed to build $dir\e[0m";
      failed+=($dir);
    fi
    echo ""
}

remove_disabled(){
    local srcds=$1
    local plugin_dir=$srcds/addons/sourcemod/plugins

    for f in $(ls $plugin_dir/disabled) ; do
        echo "removing $f from $plugin_dir"
        rm -f $f
    done
}

# fistful of frags - main
build_fof_main(){
    local srcds=$FOF
    build_server $srcds

    build admin-support $srcds
    build advanced-ads $srcds
    build analytics $srcds
    build death-chance-fof $srcds
    build dmr $srcds
    build fashion-fof $srcds
    build geoip-ext $srcds
    build killer-info-display $srcds
    build mapconfigs $srcds
    build mapfix-fof $srcds
    build navfile-blocker-ext $srcds
    build randomize-teams-fof $srcds
    build sourcebans-pp/game $srcds
    build super-kick-fof $srcds
    build voice-warn $srcds
    build weapon-only-fof $srcds
    build word-filter $srcds

    remove_disabled $srcds
}

# fistful of frags - gun game
build_fof_gg(){
    local srcds=$GGF
    build_server $srcds

    build admin-support $srcds
    build advanced-ads $srcds
    build analytics $srcds
    build death-chance-fof $srcds
    build dmr $srcds
    build fashion-fof $srcds
    build geoip-ext $srcds
    build ggf $srcds
    build killer-info-display $srcds
    build mapconfigs $srcds
    build navfile-blocker-ext $srcds
    build mapfix-fof $srcds
    build randomize-teams-fof $srcds
    build sourcebans-pp/game $srcds
    build super-kick-fof $srcds
    build voice-warn $srcds
    build word-filter $srcds

    remove_disabled $srcds
}

# fistful of frags - gun game (12 man)
build_fof_gg2(){
    local srcds=$GGF2
    build_server $srcds

    build admin-support $srcds
    build advanced-ads $srcds
    build analytics $srcds
    build death-chance-fof $srcds
    build dmr $srcds
    build fashion-fof $srcds
    build geoip-ext $srcds
    build ggf $srcds
    build killer-info-display $srcds
    build mapconfigs $srcds
    build navfile-blocker-ext $srcds
    build mapfix-fof $srcds
    build randomize-teams-fof $srcds
    build sourcebans-pp/game $srcds
    build super-kick-fof $srcds
    build voice-warn $srcds
    build weapon-only-fof $srcds
    build word-filter $srcds

    remove_disabled $srcds
}

# fistful of frags - zombies
build_fof_foz(){
    local srcds=$FOZ
    build_server $srcds

    build admin-support $srcds
    build advanced-ads $srcds
    build analytics $srcds
    build death-chance-fof $srcds
    build dmr $srcds
    build fashion-fof $srcds
    build foz $srcds
    build geoip-ext $srcds
    build killer-info-display $srcds
    build mapconfigs $srcds
    build mapfix-fof $srcds
    build navfile-blocker-ext $srcds
    build randomize-teams-fof $srcds
    build sourcebans-pp/game $srcds
    build super-kick-fof $srcds
    build voice-warn $srcds
    build weapon-only-fof $srcds
    build word-filter $srcds

    remove_disabled $srcds
}


# fistful of frags - mario kart
build_fof_mk(){
    local srcds=$MKF
    build_server $srcds

    build admin-support $srcds
    build advanced-ads $srcds
    build analytics $srcds
    build death-chance-fof $srcds
    build dmr $srcds
    build fashion-fof $srcds
    build geoip-ext $srcds
    build killer-info-display $srcds
    build mapconfigs $srcds
    build mapfix-fof $srcds
    build navfile-blocker-ext $srcds
    build near-map-end-fof $srcds
    build randomize-teams-fof $srcds
    build sourcebans-pp/game $srcds
    build super-kick-fof $srcds
    build voice-warn $srcds
    build weapon-only-fof $srcds
    build word-filter $srcds

    remove_disabled $srcds
}

# build plugins for servers

build_fof_main
build_fof_gg
build_fof_gg2
build_fof_mk
build_fof_foz

echo ""
echo "install complete"

if [ ${#failed[@]} -eq 0 ]; then
  echo -e "\e[0;32mno plugins failed to build\e[0m";
else
  failed=($(echo "${failed[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '));
  echo -e "failed to build:\e[1;31m ${failed[@]}\e[0m";
fi
