#!/bin/bash

spcomp=$SOURCEMOD_DIR/scripting/spcomp
failed=()

build_server(){
    local server=$1

    echo "#########################"
    echo "Building Server ($server)"
    echo "#########################"
}

build(){
    local dir=$1
    local srcds=$2

    echo "building $dir for $srcds"

    make all install -C$dir SPCOMP=$spcomp SPFLAGS="-v0" SRCDS=$srcds

    # use this instead for a dry run to find errors/warnings
    # make all -C$dir SPCOMP=$spcomp SPFLAGS="-v0 -E" SRCDS=$srcds

    if [ $? -eq 0 ]; then
      echo -e "\e[0;32mfinished $dir\e[0m";
    else
      echo -e "\e[1;31mfailed to build $dir\e[0m";
      failed+=($dir);
    fi
    echo ""
}

remove_disabled(){
    local srcds=$1
    local plugin_dir=$srcds/addons/sourcemod/plugins

    for f in $(ls $plugin_dir/disabled) ; do
        echo "removing $f from $plugin_dir"
        rm -f $f
    done
}

# fistful of frags - main
build_fof_main(){
    local srcds=$HOME/steamcmd/fof_main/fof
    build_server $srcds

    build admin_support $srcds
    build advanced_ads $srcds
    build analytics $srcds
    build autoupdater $srcds
    build death_chance_fof $srcds
    build dmr $srcds
    build fashion_fof $srcds
    build killer_info_display $srcds
    build mapconfigs $srcds
    build mapfix_fof $srcds
    build navfile_blocker $srcds
    build randomize_teams_fof $srcds
    build resize_players $srcds
    build sourcebans-pp/game $srcds
    build super_kick_fof $srcds
    build voice_warn $srcds
    build weapon_only_fof $srcds
    build word_filter $srcds

    remove_disabled $srcds
}

# fistful of frags - gun game
build_fof_gg(){
    local srcds=$HOME/steamcmd/fof_gg/fof
    build_server $srcds

    build admin_support $srcds
    build advanced_ads $srcds
    build analytics $srcds
    build autoupdater $srcds
    build death_chance_fof $srcds
    build dmr $srcds
    build fashion_fof $srcds
    build gungame_fof $srcds
    build killer_info_display $srcds
    build mapconfigs $srcds
    build navfile_blocker $srcds
    build mapfix_fof $srcds
    build randomize_teams_fof $srcds
    build resize_players $srcds
    build sourcebans-pp/game $srcds
    build super_kick_fof $srcds
    build voice_warn $srcds
    build word_filter $srcds

    remove_disabled $srcds
}

# fistful of frags - gun game (12 man)
build_fof_gg2(){
    local srcds=$HOME/steamcmd/fof_gg2/fof
    build_server $srcds

    build admin_support $srcds
    build advanced_ads $srcds
    build analytics $srcds
    build autoupdater $srcds
    build death_chance_fof $srcds
    build dmr $srcds
    build fashion_fof $srcds
    build gungame_fof $srcds
    build killer_info_display $srcds
    build mapconfigs $srcds
    build navfile_blocker $srcds
    build mapfix_fof $srcds
    build randomize_teams_fof $srcds
    build resize_players $srcds
    build sourcebans-pp/game $srcds
    build super_kick_fof $srcds
    build voice_warn $srcds
    build weapon_only_fof $srcds
    build word_filter $srcds

    remove_disabled $srcds
}

# fistful of frags - zombies
build_fof_foz(){
    local srcds=$HOME/steamcmd/fof_foz/fof
    build_server $srcds

    build admin_support $srcds
    build advanced_ads $srcds
    build analytics $srcds
    build death_chance_fof $srcds
    build dmr $srcds
    build fashion_fof $srcds
    build foz $srcds
    build killer_info_display $srcds
    build mapconfigs $srcds
    build mapfix_fof $srcds
    build navfile_blocker $srcds
    build randomize_teams_fof $srcds
    build sourcebans-pp/game $srcds
    build super_kick_fof $srcds
    build voice_warn $srcds
    build weapon_mod $srcds
    build weapon_only_fof $srcds
    build word_filter $srcds

    remove_disabled $srcds
}


# fistful of frags - mario kart
build_fof_mk(){
    local srcds=$HOME/steamcmd/fof_mk/fof
    build_server $srcds

    build admin_support $srcds
    build advanced_ads $srcds
    build analytics $srcds
    build autoupdater $srcds
    build death_chance_fof $srcds
    build dmr $srcds
    build fashion_fof $srcds
    build killer_info_display $srcds
    build mapconfigs $srcds
    build mapfix_fof $srcds
    build navfile_blocker $srcds
    build near_map_end_fof $srcds
    build randomize_teams_fof $srcds
    build resize_players $srcds
    build sourcebans-pp/game $srcds
    build super_kick_fof $srcds
    build voice_warn $srcds
    build weapon_only_fof $srcds
    build word_filter $srcds

    remove_disabled $srcds
}

# build plugins for servers

build_fof_main
build_fof_gg
build_fof_gg2
build_fof_mk
build_fof_foz

echo ""
echo "install complete"

if [ ${#failed[@]} -eq 0 ]; then
  echo -e "\e[0;32mno plugins failed to build\e[0m";
else
  failed=($(echo "${failed[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '));
  echo -e "failed to build:\e[1;31m ${failed[@]}\e[0m";
fi
