#!/bin/sh

BUILD_DIR=$HOME/sourcemod/
PLUGIN_DIR=addons/sourcemod/plugins/
SPCOMP=$SOURCEMOD_DIR/scripting/spcomp
#SPCOMP=$SOURCEMOD_DIR_1_10/scripting/spcomp

build_server(){
    local server=$1
    cd $BUILD_DIR

    echo "#########################"
    echo "Building Server ($server)"
    echo "#########################"
}

build(){
    local dir=$1
    local srcds=$2
    make -C$dir SPCOMP=$SPCOMP | grep --color "warning\|error"
    # make -C$dir install
    cd $BUILD_DIR
}

remove_disabled(){
    local srcds=$1

    cd $srcds/$PLUGIN_DIR
    for f in $(ls disabled) ; do
        rm -f $f
    done
}

# fistful of frags - main
build_fof_main(){
    local srcds=$HOME/steamcmd/fof_main/fof/
    build_server $srcds

    build admin_support $srcds
    build advanced_ads $srcds
    build analytics $srcds
    build autoupdater $srcds
    build death_chance_fof $srcds
    build dmr $srcds
    build fashion_fof $srcds
    build killer_info_display $srcds
    build mapconfigs $srcds
    build mapfix_fof $srcds
    build navfile_blocker $srcds
    build randomize_teams_fof $srcds
    build resize_players $srcds
    build sourcebans-pp/game $srcds
    build super_kick_fof $srcds
    build voice_warn $srcds
    build weapon_only_fof $srcds
    build word_filter $srcds

    remove_disabled $srcds
}

# fistful of frags - gun game
build_fof_gg(){
    local srcds=$HOME/steamcmd/fof_gg/fof/
    build_server $srcds

    build admin_support $srcds
    build advanced_ads $srcds
    build analytics $srcds
    build autoupdater $srcds
    build death_chance_fof $srcds
    build dmr $srcds
    build fashion_fof $srcds
    build gungame_fof $srcds
    build killer_info_display $srcds
    build mapconfigs $srcds
    build navfile_blocker $srcds
    build mapfix_fof $srcds
    build randomize_teams_fof $srcds
    build resize_players $srcds
    build sourcebans-pp/game $srcds
    build super_kick_fof $srcds
    build voice_warn $srcds
    build word_filter $srcds

    remove_disabled $srcds
}

# fistful of frags - gun game (12 man)
build_fof_gg2(){
    local srcds=$HOME/steamcmd/fof_gg2/fof/
    build_server $srcds

    build admin_support $srcds
    build advanced_ads $srcds
    build analytics $srcds
    build autoupdater $srcds
    build death_chance_fof $srcds
    build dmr $srcds
    build fashion_fof $srcds
    build gungame_fof $srcds
    build killer_info_display $srcds
    build mapconfigs $srcds
    build navfile_blocker $srcds
    build mapfix_fof $srcds
    build randomize_teams_fof $srcds
    build resize_players $srcds
    build sourcebans-pp/game $srcds
    build super_kick_fof $srcds
    build voice_warn $srcds
    build weapon_only_fof $srcds
    build word_filter $srcds

    remove_disabled $srcds
}

# fistful of frags - zombies
build_fof_foz(){
    local srcds=$HOME/steamcmd/fof_foz/fof/
    build_server $srcds

    build admin_support $srcds
    build advanced_ads $srcds
    build analytics $srcds
    build death_chance_fof $srcds
    build dmr $srcds
    build fashion_fof $srcds
    build foz $srcds
    build killer_info_display $srcds
    build mapconfigs $srcds
    build mapfix_fof $srcds
    build navfile_blocker $srcds
    build randomize_teams_fof $srcds
    build sourcebans-pp/game $srcds
    build super_kick_fof $srcds
    build voice_warn $srcds
    build weapon_mod $srcds
    build weapon_only_fof $srcds
    build word_filter $srcds

    remove_disabled $srcds
}


# fistful of frags - mario kart
build_fof_mk(){
    local srcds=$HOME/steamcmd/fof_mk/fof/
    build_server $srcds

    build admin_support $srcds
    build advanced_ads $srcds
    build analytics $srcds
    build autoupdater $srcds
    build death_chance_fof $srcds
    build dmr $srcds
    build fashion_fof $srcds
    build killer_info_display $srcds
    build mapconfigs $srcds
    build mapfix_fof $srcds
    build navfile_blocker $srcds
    build near_map_end_fof $srcds
    build randomize_teams_fof $srcds
    build resize_players $srcds
    build sourcebans-pp/game $srcds
    build super_kick_fof $srcds
    build voice_warn $srcds
    build weapon_only_fof $srcds
    build word_filter $srcds

    remove_disabled $srcds
}

# build plugins for servers

#build_fof_main
#build_fof_gg
#build_fof_gg2
build_fof_mk
#build_fof_foz
