#!/bin/sh
# https://github.com/bcserv/sourcemod-updater

# dev repos
~/bin/sourcemod-updater/update.sh ~/sourcemod/sm-1.8/ --snapshot-stable --dontask
~/bin/sourcemod-updater/update.sh ~/sourcemod/sm-1.9/ --snapshot-dev --install --dontask

# game servers
~/bin/sourcemod-updater/update.sh ~/steamcmd/fof_main/fof/ --snapshot-stable --dontask
~/bin/sourcemod-updater/update.sh ~/steamcmd/fof_gg/fof/ --snapshot-stable --dontask
~/bin/sourcemod-updater/update.sh ~/steamcmd/fof_gg2/fof/ --snapshot-stable --dontask
~/bin/sourcemod-updater/update.sh ~/steamcmd/fof_foz/fof/ --snapshot-stable --dontask
~/bin/sourcemod-updater/update.sh ~/steamcmd/fof_mk/fof/ --snapshot-stable --dontask

# NOTE to update manually to a specific version use:
# ~/bin/sourcemod-updater/update.sh ~/steamcmd/fof_foz/fof/ "http://www.sourcemod.net/smdrop/1.8/sourcemod-1.8.0-git6044-linux.tar.gz"
