#!/bin/sh
./steamcmd.sh +runscript nmrih_main.txt
tar -xzf ~/sourcemod/mmsource-1.10.6-git942-linux.tar.gz  -C ~/steamcmd/nmrih_main/nmrih/
~/bin/sourcemod-updater/update.sh ~/steamcmd/nmrih_main/nmrih/ --install --dontask
