#!/bin/sh
./steamcmd.sh +runscript l4d2_main.txt
tar -xzf ~/sourcemod/mmsource-1.10.4-git923-linux.tar.gz -C ~/steamcmd/l4d2_main/left4dead2/
~/bin/sourcemod-updater/update.sh ~/steamcmd/l4d2_main/left4dead/ --install --dontask
